name: Oistarian-NEXUS-ONE-APP
description: Oistarian NEXUS ONE APP infrastructure
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: azure-typescript
